version: "3"

services:

  db:
    image: postgres:9.4
    container_name: db

  proxy:
    image: yiliao/proxy:v2
    ports:
      - "8080:80"

  vote:
    image: yiliao/vote:v1
    ports:
      - "5000:80"

  redis:
    image: redis:alpine
    container_name: redis
    ports: ["6379"]

  result:
    image: yiliao/result:v1
    ports:
      - "5001:80"
      - "5858:5858"

  worker:
    image: yiliao/worker:v1
